W7D3/musicapp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands, only: [:index, :create, :new, :edit, :show, :update, :destroy]

end

W7D3/musicapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W7D3/musicapp/app/models/band.rb
class Band < ApplicationRecord

    validates :name, presence: true
end

W7D3/musicapp/app/models/user.rb
class User < ApplicationRecord

    after_initialize :ensure_session_token

    attr_reader :password

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)

        return nil if user.nil?
        user.is_password?(password) ? user : nil
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
      end

    def self.generate_session_token
        SecureRandom.urlsafe_base64(16)
    end

    def reset_session_token
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
    end

    private

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end
end

W7D3/musicapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    helper_method :logged_in?


    def current_user
        return nil unless session[:session_token]
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        return nil unless session[:session_token]
    end
    
    def login_user!(user)
        session[:session_token] = user.reset_session_token
    end

    def logout_user!
        current_user.reset_session_token
    end
end

W7D3/musicapp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def index
        @bands = Band.all
        render :index
    end

    def create
        @band = Band.new(band_params)
        if @band.save!
            redirect_to band_url(@band)
        else
            flash.now[:errors] = @user.errors.full_messages
        end
    end

    def new
        @band = Band.new
        render :new
    end

    def show
        @band = Band.find(params[:id])
        render :show
    end

    def edit
        @band = Band.find(params[:id])
        render :edit
    end

    def update
        @band = Band.find(params[:id])
        if @band.update_attributes(band_params)
          redirect_to band_url(@band)
        else
          flash.now[:errors] = @band.errors.full_messages
          render :edit
        end
      end
    private

    def band_params
        params.require(:band).permit(:name)
    end
end

W7D3/musicapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    # before_action :require_no_user!, only: %i(create new)
  
    def new
        render :new
    end

    def create
      @user = User.find_by_credentials(
        params[:user][:email],
        params[:user][:password]
      )
  
      if @user.nil?
        flash.now[:errors] = ["Incorrect username and/or password"]
        render :new
      else
        login_user!(@user)
        redirect_to user_url(@user)
      end
    end
  
    def destroy
      logout_user!
      redirect_to new_session_url
    end
  
    
  end
  

W7D3/musicapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
    # before_action :require_no_user

    def create
        @user = User.new(user_params)
        if @user.save!
            login_user!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
        end
    end

    def new
        @user = User.new
        render :new
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    private

    def user_params
        params.require(:user).permit(:email, :password)
    end
end

W7D3/musicapp/app/helpers/application_helper.rb
module ApplicationHelper
end

W7D3/musicapp/app/views/bands/edit.html.erb
<section class="page">
  <div class="centered-box">
    <h1>Edit Band</h1>

    <form action="<%= band_url(@band) %>" method="post">
    <input type="hidden" name="_method" value="<%= :patch %>">
      <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

      <label for="band_name">Name</label>
      <input type="text"
        name="band[name]"
        id="band_name"
        value="<%= @band.name %>">
      <br>

      <input type="submit">
    </form>
  </div>
</section>

W7D3/musicapp/app/views/bands/index.html.erb
<ul>
    <% @bands.each do |band|%>
        <li><%= band.name %></li>
    <% end %>
</ul>

W7D3/musicapp/app/views/bands/new.html.erb
<section class="page">
  <div class="centered-box">
    <h1>New Band</h1>

    <form action="<%= bands_url %>" method="post">
      <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

      <label for="band_name">Name</label>
      <input type="text"
        name="band[name]"
        id="band_name"
        value="<%= @band.name %>">
      <br>

      <input type="submit">
    </form>
  </div>
</section>

W7D3/musicapp/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

W7D3/musicapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musicapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <h1>Music App</h1>
    <% if current_user.nil? %>
      <a href="<%= new_session_url %>">Sign in</a>
      <a href="<%= new_user_url %>">Sign up</a>
    <% else %>
      <form action="<%= session_url %>" method="post">
        <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Logout">
      </form>
    <% end %>
  </header>
  <body>

    <%= yield %>
  </body>
</html>

W7D3/musicapp/app/views/users/new.html.erb
<section class="page">
  <div class="centered-box">
    <h1>New User</h1>

    <form action="<%= users_url %>" method="post">
      <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

      <label for="user_email">Email</label>
      <input type="text"
        name="user[email]"
        id="user_email"
        value="<%= @user.email %>">
      <br>

      <label for="user_password">Password</label>
      <input type="password"
        name="user[password]"
        id="user_password"
        value="<%= @user.password %>">
      <br>

      <input type="submit">
    </form>
  </div>
</section>

W7D3/musicapp/app/views/users/show.html.erb
<h1><%= @user.email %></h1>